# Generated by Django 6.1 on 2026-09-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='quote',
            field=models.CharField(blank=True, max_length=240, verbose_name='Cita'),
        ),
    ]
